version: 0.6.0

namespace: eventlane
project: frontend-admin

services:
  - name: admin-web
    image: ghcr.io/markmorcos/eventlane-admin-web
    context: frontend
    dockerfile: apps/admin/Dockerfile
    port: 80
    resources:
      requests:
        cpu: 25m
        memory: 32Mi
      limits:
        cpu: 200m
        memory: 64Mi
    startupProbe:
      httpGet:
        path: /
        port: 80
      initialDelaySeconds: 2
      periodSeconds: 2
      failureThreshold: 15
    livenessProbe:
      httpGet:
        path: /
        port: 80
      periodSeconds: 30
      timeoutSeconds: 5
      failureThreshold: 3
    readinessProbe:
      httpGet:
        path: /
        port: 80
      periodSeconds: 10
      timeoutSeconds: 3
      failureThreshold: 3
    terminationGracePeriodSeconds: 15
    ingress:
      host: admin.eventlane.io
      path: /?(.*)
      pathType: ImplementationSpecific
